language: node_js
node_js:
  - "0.10"
  - "0.11"

before_script:
  - npm install --quiet -g grunt-cli karma
  - npm install
  - npm install -g bower
  - bower install -f --clean

script: grunt default coveralls
notifications:
  email: false